### ISSUE TITLE
Share a database dump

### ISSUE THREAD

**Issue by rick02840** [savaslabs/durham-civil-rights-map#82]
Hi,
Any chance you could share a database dump?  Anything with sample content would be fine.  I know that's asking a lot, so no worries if not.
I am following your post here: http://savaslabs.com/2015/07/06/map-in-drupal-8.html  < thanks for that!  But realized I could get further faster with this repo.  I am working on a non-profit thing "light up the map" for the Western Mass group of Mothers Out Front. 
Thanks,
Rick
richardblakehood@gmail.com

**Comment by chrisarusso** [comment]
Sorry @rick02840. This request was just brought to my attention. I must have missed the initial email. I'm assuming the time has come and gone since this would be useful to you. Let me know if you're still interested.
